---
title: "Problem 2.5: Why social networks are not \"well-mixed\""
---

\newcommand\exprobi{{\varepsilon_i}}
\newcommand\exprob{{\bar\varepsilon}}

For our purposes, a _well-mixed_ population is a hypothetical 
one where any one person is equally
likely to encounter anyone else. This matters for calculating the _exposure
probability_ for individual $i$, $\exprobi$, which is the probability that
a person doing legacy behavior $L$ observes or learns from someone doing
behavior $A$. If we also assume that the population is large
enough so that $N \approx N - 1$, then $\exprobi = \frac{A}{N}$ for everyone
(i.e., for all $i$). 
In the difference and differential equations versions of the LAL model, and
in the analytical payoff-biased social learning model, the well-mixed assumption
enables the formal calculation of equilibrium adoption levels and fixation
probabilities and times. One consequence of the well-mixed assumption is that
the mean exposure probability, $\exprob$, is the same no matter which $A$
individuals have adopted the behavior.

Social networks in the real world are not well-mixed, 
since individuals can only learn from whom they meet. 
To see the consequences of this, we will see how calculate $\exprob$ 
Specifically, let's have
fun with an anachronistic situation where some of the
Florentine oligarchs have installed solar panels. Let's pretend that if
families have intermarried, then they might communicate about solar
panel installation with one another. If there's no intermarriage, they don't
talk about sustainable adaptations. 

In this problem, you will write code to calculate $\exprobi$, 
filling in key parts of a function called `exposure_probability` in file
`PS2/expoprob.R`. You will then use it to calculate the exposure probability
for different values of $A$, first in the Florentine network and then in 
lattice networks and small-world networks with different edge randomization
probabilities, $p$.


## Write a function to calculate *exposure probability* $\exprobi$ and $\exprob$

In this problem you will edit `expoprob.R` here in the PS2 directory, which
the _individual_ and _global exposure
probability_, i.e., the probability that someone doing a legacy behavior
encounters someone doing $A$, and is thereby _exposed to_ $A$. 

